### ISSUE TITLE
slice indexing broken

### ISSUE THREAD

**Issue by oli-obk** [tsion/miri#8]
The following piece of code triggers [this assertion](https://github.com/tsion/miri/blob/master/src/interpreter.rs#L1182)

```rust
#[miri_run]
fn slice() -> u8 {
    let arr: &[_] = &[101, 102, 103, 104, 105, 106];
    arr[5]
}
```

**Comment by tsion** [comment]
Lvalue handling in general needs an overhaul. I'll try to clean it up and fix this at the same time (though the fix for this could be trivial).

**Comment by tsion** [comment]
I fixed this in my `new-data-layout` branch, which I'll merge into master once it passes all tests.
